export const TABLET_SCREEN_WIDTH = 769;
export const PHONE_SCREEN_WIDTH = 481;
export const NUMBER_INITIALLY_MOVIES_TABLET = 8;
export const NUMBER_INITIALLY_MOVIES_PHONE = 5;
export const NUMBER_INITIALLY_MOVIES_LAPTOP = 12;
export const NUMBER_ADDED_MOVIES_TABLET = 2;
export const NUMBER_ADDED_MOVIES_PHONE = 3;
export const NUMBER_ADDED_MOVIES_LAPTOP = 3;